/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.lanwen.pulsar.functions;


import org.apache.pulsar.client.admin.PulsarAdmin;
import org.apache.pulsar.client.admin.PulsarAdminException;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;
import org.apache.pulsar.client.api.SubscriptionInitialPosition;
import org.apache.pulsar.client.api.SubscriptionType;
import org.apache.pulsar.common.functions.FunctionConfig;
import org.apache.pulsar.functions.LocalRunner;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PulsarContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import reactor.core.Disposable;

import java.time.Duration;
import java.util.List;
import java.util.UUID;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class IntegrationTest {

    private static final PulsarContainer PULSAR = new PulsarContainer("2.5.0")
            .withCommand("bin/pulsar", "standalone")
//            .withLogConsumer(outputFrame -> System.out.print(outputFrame.getUtf8String()))
            .waitingFor(Wait.forLogMessage(".*Function worker service started.*", 1));

    static final String FUNCTIONS_JAR_PATH_PROPERTY = "functions.jar.path";
    static final String FUNCTIONS_RAW_JAR_PATH_PROPERTY = "functions.raw.jar.path";
    static final String TEST_INPUTS_TOPIC = "test-inputs-topic";
    static final String TEST_OUTPUT_TOPIC = "test-output-topic";
    static final String TEST_OUTPUT_CTX_TOPIC = "test-output-ctx-topic";
    static final String TEST_DLQ_TOPIC = "test-dlq-topic";
    static final String TEST_LOG_TOPIC = "test-log-topic";

    private static PulsarAdmin pulsarAdmin;
    private static PulsarClient pulsarClient;

    static {
        PULSAR.setPortBindings(List.of(
                "8080:" + PulsarContainer.BROKER_HTTP_PORT,
                "6650:" + PulsarContainer.BROKER_PORT
        ));
        PULSAR.start();
    }

    @BeforeAll
    static void beforeAll() throws PulsarClientException, PulsarAdminException {
        pulsarAdmin = PulsarAdmin.builder()
//                .serviceHttpUrl("http://localhost:8080")
                .serviceHttpUrl(PULSAR.getHttpServiceUrl())
                .build();

        pulsarClient = PulsarClient.builder()
//                .serviceUrl("pulsar://localhost:6650")
                .serviceUrl(PULSAR.getPulsarBrokerUrl())
                .build();

        pulsarAdmin.topics().createPartitionedTopic(TEST_INPUTS_TOPIC, 3);
        pulsarAdmin.topics().createPartitionedTopic(TEST_OUTPUT_TOPIC, 3);
    }

    FunctionConfig.FunctionConfigBuilder confSimple = FunctionConfig.builder()
            .tenant("public")
            .namespace("default")
            .name("exclamation")
            .retainOrdering(true)
            .inputs(List.of(TEST_INPUTS_TOPIC))
            .output(TEST_OUTPUT_TOPIC)
            .className(ExclamationFunction.class.getName())
            .jar(System.getProperty(FUNCTIONS_JAR_PATH_PROPERTY))
            .runtime(FunctionConfig.Runtime.JAVA);

    FunctionConfig.FunctionConfigBuilder confSerde = FunctionConfig.builder()
            .tenant("public")
            .namespace("default")
            .name(UUID.randomUUID().toString())
            .retainOrdering(true)
            .inputs(List.of(TEST_INPUTS_TOPIC))
            .output(TEST_OUTPUT_TOPIC)
            .deadLetterTopic(TEST_DLQ_TOPIC)
            .maxMessageRetries(2)
            .logTopic(TEST_LOG_TOPIC)
            .jar(System.getProperty(FUNCTIONS_JAR_PATH_PROPERTY))
            .className(SerDeFunction.class.getName())
            .runtime(FunctionConfig.Runtime.JAVA);

    @Test
    public void shouldRunSimpleFunction() throws Exception {
        LocalRunner.builder().functionConfig(confSimple.build()).build().start(false);

        Disposable publisher = Producer.string(pulsarClient, TEST_INPUTS_TOPIC).subscribe();
        Disposable listener = Consumer.consumer(pulsarClient, TEST_INPUTS_TOPIC).subscribe();
        Consumer.consumer(pulsarClient, TEST_OUTPUT_TOPIC)
                .doOnTerminate(publisher::dispose)
                .doOnTerminate(listener::dispose)
                .blockLast(Duration.ofMinutes(10));
    }

    @Test
    public void shouldRunSimpleFunctionCluster() throws Exception {
        pulsarAdmin.functions().createFunction(confSimple.build(), System.getProperty(FUNCTIONS_JAR_PATH_PROPERTY));

        Disposable subscribe = Producer.string(pulsarClient, TEST_INPUTS_TOPIC).log().subscribe();
        Long inputCnt = Consumer.consumer(pulsarClient, TEST_INPUTS_TOPIC).doOnTerminate(subscribe::dispose).log().take(2).count().block(Duration.ofMinutes(1));
        Long outCnt = Consumer.consumer(pulsarClient, TEST_OUTPUT_TOPIC).take(2).count().block(Duration.ofMinutes(1));

        assertThat(inputCnt, is(outCnt));
    }

    @Test
    public void shouldRunSerDeFunction() throws Exception {
        LocalRunner.builder().functionConfig(confSerde.build()).build().start(false);

        Disposable publisher = Producer.json(pulsarClient, TEST_INPUTS_TOPIC).subscribe();
        Disposable listener = Consumer.consumer(pulsarClient, TEST_INPUTS_TOPIC).subscribe();
        Disposable listenerdlq = Consumer.consumer(pulsarClient, TEST_DLQ_TOPIC).subscribe();
        Disposable listenerlog = Consumer.consumer(pulsarClient, TEST_LOG_TOPIC).subscribe();
        Consumer.consumer(pulsarClient, TEST_OUTPUT_TOPIC)
                .doOnTerminate(publisher::dispose)
                .doOnTerminate(listener::dispose)
                .doOnTerminate(listenerlog::dispose)
                .doOnTerminate(listenerdlq::dispose)
                .blockLast(Duration.ofMinutes(10));
    }

    @Test
    public void shouldRunSerDeFunctionCluster() throws Exception {
        String subname = UUID.randomUUID().toString();
        FunctionConfig conf = confSerde.subName(subname).build();

        Producer.json(pulsarClient, TEST_INPUTS_TOPIC).take(2).blockLast(Duration.ofMinutes(1));
        Disposable listener = Consumer.consumer(pulsarClient, TEST_INPUTS_TOPIC).subscribe();

        pulsarClient.newConsumer()
                .subscriptionType(SubscriptionType.Failover)
                .consumerName("consumer-" + UUID.randomUUID())
                .subscriptionName(subname)
                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                .topic(TEST_INPUTS_TOPIC)
                .subscribe()
                .close();
        pulsarAdmin.functions().createFunction(conf, System.getProperty(FUNCTIONS_JAR_PATH_PROPERTY));

        Disposable publisher = Producer.json(pulsarClient, TEST_INPUTS_TOPIC).subscribe();
        Disposable listenerdlq = Consumer.consumer(pulsarClient, TEST_DLQ_TOPIC).subscribe();
        Disposable listenerlog = Consumer.consumer(pulsarClient, TEST_LOG_TOPIC).subscribe();

        System.out.println("******************");
        System.out.println(String.format(
                "docker exec %s cat /tmp/functions/%s/%s/%s/%s-0.log", PULSAR.getContainerId(),
                conf.getTenant(), conf.getNamespace(), conf.getName(), conf.getName()
        ));
        System.out.println("******************");

        Consumer.consumer(pulsarClient, TEST_OUTPUT_TOPIC)
                .doOnTerminate(publisher::dispose)
                .doOnTerminate(listener::dispose)
                .doOnTerminate(listenerlog::dispose)
                .doOnTerminate(listenerdlq::dispose)
                .blockLast(Duration.ofMinutes(10));
    }

    @Test
    public void shouldExchangeContext() throws Exception {
        Disposable listener = Consumer.consumer(pulsarClient, TEST_INPUTS_TOPIC).subscribe();
        Disposable listenerctx = Consumer.consumer(pulsarClient, TEST_OUTPUT_CTX_TOPIC).subscribe();
        Disposable listenerout = Consumer.consumer(pulsarClient, TEST_OUTPUT_TOPIC).subscribe();

        var conf = confSerde.className(WriteCtxFunction.class.getName()).build();

        var ctxconf = FunctionConfig.builder()
                .tenant("public")
                .namespace("default")
                .name(UUID.randomUUID().toString())
                .retainOrdering(true)
                .inputs(List.of(TEST_INPUTS_TOPIC))
                .output(TEST_OUTPUT_CTX_TOPIC)
                .className(SimpleCtxFunction.class.getName())
                .jar(System.getProperty(FUNCTIONS_RAW_JAR_PATH_PROPERTY))
                .runtime(FunctionConfig.Runtime.JAVA).build();

        pulsarAdmin.functions().createFunction(conf, System.getProperty(FUNCTIONS_JAR_PATH_PROPERTY));
        pulsarAdmin.functions().createFunction(ctxconf, System.getProperty(FUNCTIONS_RAW_JAR_PATH_PROPERTY));

        Disposable publisher = Producer.json(pulsarClient, TEST_INPUTS_TOPIC).subscribe();

        System.out.println("******************");
        System.out.println(String.format(
                "docker exec %s cat /tmp/functions/%s/%s/%s/%s-0.log", PULSAR.getContainerId(),
                conf.getTenant(), conf.getNamespace(), conf.getName(), conf.getName()
        ));
        System.out.println("******************");


        System.out.println("******************");
        System.out.println(String.format(
                "docker exec %s cat /tmp/functions/%s/%s/%s/%s-0.log", PULSAR.getContainerId(),
                conf.getTenant(), conf.getNamespace(), ctxconf.getName(), ctxconf.getName()
        ));
        System.out.println("******************");

        Consumer.consumer(pulsarClient, TEST_OUTPUT_TOPIC)
                .doOnTerminate(publisher::dispose)
                .doOnTerminate(listener::dispose)
                .doOnTerminate(listenerout::dispose)
                .doOnTerminate(listenerctx::dispose)
                .blockLast(Duration.ofMinutes(10));
    }

}
